env:
  es2021: true
  node: true
  jest: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  quotes: [error, 'single']
  semi: [error, 'always']
  no-trailing-spaces: error
  indent: [error, 2]
  max-len: [error, { code: 100 }]
  no-multiple-empty-lines: [error, { max: 1 }]
  padded-blocks: [error, 'never']
